import { execFileSync } from "node:child_process";
import { existsSync, mkdtempSync, readFileSync, rmSync } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";

import { expect, test } from "@playwright/test";

// Phase 3 exercises the real <input type="file"> upload flow in an actual
// browser. The fixture is a tiny synthetic clip generated by ffmpeg at test
// runtime (never committed to the repo) so this suite never depends on a
// fabricated demo binary.
let fixtureBuffer: Buffer;
let ffmpegAvailable = true;

test.beforeAll(() => {
  const dir = mkdtempSync(path.join(tmpdir(), "relaylab-phase3-"));
  const clipPath = path.join(dir, "clip.webm");
  try {
    execFileSync("ffmpeg", [
      "-y",
      "-hide_banner",
      "-loglevel",
      "error",
      "-f",
      "lavfi",
      "-i",
      "color=c=blue:s=64x36:d=1:r=5",
      "-f",
      "lavfi",
      "-i",
      "sine=frequency=440:duration=1",
      "-c:v",
      "libvpx-vp9",
      "-pix_fmt",
      "yuv420p",
      "-c:a",
      "libopus",
      "-shortest",
      clipPath,
    ]);
    if (existsSync(clipPath)) fixtureBuffer = readFileSync(clipPath);
  } catch {
    // If ffmpeg is unavailable in this environment the suite skips and
    // reports the gap honestly instead of pretending the upload flow ran.
    ffmpegAvailable = false;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
});

test.beforeEach(async ({ page }) => {
  await page.addInitScript(() => {
    interface ToolDefinition {
      name: string;
      execute: (
        input: Record<string, unknown>,
        options: { signal: AbortSignal },
      ) => unknown | Promise<unknown>;
    }

    class BrowserModelContext extends EventTarget {
      private readonly tools = new Map<string, ToolDefinition>();

      async registerTool(
        tool: ToolDefinition,
        options?: { signal?: AbortSignal },
      ): Promise<void> {
        this.tools.set(tool.name, tool);
        options?.signal?.addEventListener(
          "abort",
          () => {
            if (this.tools.get(tool.name) === tool) this.tools.delete(tool.name);
          },
          { once: true },
        );
      }

      async invoke(name: string, input: Record<string, unknown>): Promise<unknown> {
        const tool = this.tools.get(name);
        if (!tool) throw new DOMException(`Tool not found: ${name}`, "NotFoundError");
        return tool.execute(structuredClone(input), {
          signal: new AbortController().signal,
        });
      }
    }

    const modelContext = new BrowserModelContext();
    Object.defineProperty(document, "modelContext", {
      configurable: true,
      value: modelContext,
    });
    Object.defineProperty(window, "__relaylabInvoke", {
      configurable: true,
      value: (name: string, input: Record<string, unknown>) =>
        modelContext.invoke(name, input),
    });
  });
});

test("opens a genuinely blank local project and unlocks editing after base upload", async ({
  page,
}) => {
  test.skip(!ffmpegAvailable, "ffmpeg is required to synthesize a local video fixture");

  await page.goto("/");
  await expect(page.getByTestId("blank-project-preview")).toBeVisible();
  await expect(page.getByText("RelayLab", { exact: true })).toBeVisible();
  await expect(page.getByText("No B-roll moments yet.", { exact: false })).toBeVisible();
  await expect(page.getByTestId("approve-plan")).toBeDisabled();
  await expect(page.getByLabel("Upload B-roll videos")).toBeDisabled();
  await expect(page.locator("[data-overlay-id]")).toHaveCount(0);
  await expect(page.locator("[data-generation-suggestion-id]")).toHaveCount(0);

  await page.getByLabel("Upload base video").setInputFiles({
    name: "first-local-project.webm",
    mimeType: "video/webm",
    buffer: fixtureBuffer,
  });

  await expect(page.getByTestId("blank-project-preview")).toHaveCount(0);
  await expect(page.locator('video[data-base-audio-policy="master"]')).toBeVisible();
  await expect(
    page.getByText("first-local-project.webm loaded as the master base video.", {
      exact: true,
    }),
  ).toBeVisible();
  await expect(page.getByTestId("approve-plan")).toBeEnabled();
  await expect(page.getByLabel("Upload B-roll videos")).toBeEnabled();
});

test("uploads real local reels and previews one muted overlay on the base master clock", async ({
  page,
}) => {
  test.skip(!ffmpegAvailable, "ffmpeg is required to synthesize a local video fixture");

  await page.goto("/demo");
  await expect(page.getByTestId("webmcp-status")).toHaveAttribute(
    "data-status",
    "available",
  );

  await page.getByLabel("Upload base video").setInputFiles({
    name: "local-talking-head.webm",
    mimeType: "video/webm",
    buffer: fixtureBuffer,
  });
  const base = page.locator('video[data-base-audio-policy="master"]');
  await expect(base).toBeVisible();
  await expect(
    page.getByText("local-talking-head.webm loaded as the master base video.", {
      exact: true,
    }),
  ).toBeVisible();

  await page.getByLabel("Upload B-roll videos").setInputFiles([
    { name: "broll-one.webm", mimeType: "video/webm", buffer: fixtureBuffer },
    { name: "broll-two.webm", mimeType: "video/webm", buffer: fixtureBuffer },
  ]);
  await expect(page.getByText("2 B-roll reels loaded as video-only sources.")).toBeVisible();
  await expect(page.getByText("broll-one.webm", { exact: true })).toBeVisible();
  await expect(page.getByText("broll-two.webm", { exact: true })).toBeVisible();

  const proposal = (await page.evaluate(async () => {
    const invoke = (window as unknown as {
      __relaylabInvoke: (
        name: string,
        input: Record<string, unknown>,
      ) => Promise<unknown>;
    }).__relaylabInvoke;
    const search = (await invoke("search_broll", {
      query: "one",
      limit: 1,
    })) as { results: { momentId: string }[] };
    if (!search.results[0]) throw new Error("Uploaded B-roll was not indexed");
    return invoke("propose_overlay", {
      momentId: search.results[0].momentId,
      timelineStart: 0,
      duration: 0.8,
      reason: "Verify the local video-only preview path.",
    });
  })) as { ok: boolean; overlayId: string };
  expect(proposal.ok).toBe(true);
  await expect(page.getByTestId(`overlay-${proposal.overlayId}`)).toBeVisible();

  const broll = page.getByLabel("Muted B-roll preview: broll-one.webm");
  await expect(broll).toBeVisible();
  await expect(page.locator("video")).toHaveCount(2);
  expect(await base.evaluate((video: HTMLVideoElement) => video.muted)).toBe(false);
  expect(await broll.evaluate((video: HTMLVideoElement) => video.muted)).toBe(true);

  await page.getByRole("button", { name: "Play preview" }).click();
  await expect(page.getByRole("button", { name: "Pause preview" })).toBeVisible();
  await expect
    .poll(() => base.evaluate((video: HTMLVideoElement) => video.currentTime))
    .toBeGreaterThan(0.15);
  await expect
    .poll(async () => {
      const baseTime = await base.evaluate((video: HTMLVideoElement) => video.currentTime);
      const brollTime = await broll.evaluate((video: HTMLVideoElement) => video.currentTime);
      return Math.abs(baseTime - brollTime);
    })
    .toBeLessThan(0.3);
  expect(await base.evaluate((video: HTMLVideoElement) => video.paused)).toBe(false);
  expect(await broll.evaluate((video: HTMLVideoElement) => video.muted)).toBe(true);
  await page.getByRole("button", { name: "Pause preview" }).click();

  await page.screenshot({
    path: path.join(process.cwd(), "relaylab-phase3.png"),
    fullPage: true,
  });

  await page.getByLabel("Upload base video").setInputFiles({
    name: "replacement-base.webm",
    mimeType: "video/webm",
    buffer: fixtureBuffer,
  });
  await expect(
    page.getByText("replacement-base.webm loaded as the master base video.", {
      exact: true,
    }),
  ).toBeVisible();
  await expect(page.getByTestId(`overlay-${proposal.overlayId}`)).toHaveCount(0);
  await expect(page.getByLabel(/Muted B-roll preview:/)).toHaveCount(0);
});
